### ISSUE TITLE
Error on createOrder

### ISSUE THREAD

**Issue by wannesdemaeght** [Satoshinaire/kucoin-api#4]
First of, I've already placed 287 succesful orders with this library.
Today, all of the sudden, I began getting orders when placing an order.
As this is a fully automated trader, it is programmed to try again when getting an error.

However, although the response was an error, all orders were succesfully posted and filled, so something must have gone wrong, but I have no idea what.

Errorlog:

> { NotFoundError
>     at ClientRequest.onResponse (C:\Trader\Logic\node_modules\restify-clients\lib\HttpClient.js:217:26)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
>     at TLSSocket.socketOnData (_http_client.js:440:20)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12) jse_shortmsg: '', jse_info: {}, message: '', body: {} }

**Comment by wannesdemaeght** [comment]
Ok, since this first time, my trader posted another 24 orders.
16 of them worked perfectly, 8 of them returned this weird error.

I have lost too much funds because of this bug, and as there apparently is no support whatsoever, I'm moving over to ccxt.
